server:
  port: 8080
  servlet:
    context-path: /yuko

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/eslkan
    username: root
    password: Aa778899
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  typeAliasesPackage: com.chanshiyu.yuko.entity

logging:
  level:
    com.chanshiyu.yuko: debug

jwt:
  tokenHeader: Authorization
  tokenHead: Bearer
  secret: yuko-secret
  expiration: 604800

disruptor:
  buffer:
    size: 1048576

swagger:
  title: Yuko Api
  description: Yuko Api
  version: 1.0.0
  terms-of-service-url: https://chanshiyu.com/
  base-package: com.chanshiyu.yuko
  base-path: /**
  contact:
    name: 蝉時雨
    url: https://chanshiyu.com/
    email: me@chanshiyu.com
  authorization:
    name: Authorization
    type: ApiKey
    key-name: token
    auth-regex: ^.*$